server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: weather-report-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/weather/**

        - id: alert-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/alerts/**

        - id: alert-websocket
          uri: ws://localhost:8083
          predicates:
            - Path=/api/alerts/ws
          filters:
            - StripPrefix=1

        - id: statistics-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/statistics/**

        - id: storage-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/storage/**
